### ISSUE TITLE
Vista turno cliente

### ISSUE THREAD

**Issue by alanmdza** [alanmdza/TrimTrack#11]
Tabla Cliente

-  DNI
-  Telefono

Tabla Admin(Modificar)

- Usuario
- Constraseña

Tabla turno

- Datetime
- Cliente
- Servicio

Checkar que un servicio pueda no tener precio

Eliminar tabla usuario

Lógica de la api

La lógica gira alrededor de los turnos

- Obtener el dni del cliente del request, si existe el cliente asignar el existente. Si no crearlo y asignarlo. A considerar: Si existe pero el teléfono es diferente, actualizarlo
- Checkear que el turno sea un múltiplo de media hora. y que esté displonible

**Comment by RichterLeandro** [comment]
Checkar que un servicio pueda no tener precio

Lógica de la api

La lógica gira alrededor de los turnos

- [x] Obtener el dni del cliente del request, si existe el cliente asignar el existente. Si no crearlo y asignarlo. 

- [ ] Checkear que el turno sea un múltiplo de media hora. y que esté displonible

y el tema de la tabla de bloqueo
